### ISSUE TITLE
Delete button on loadouts doesn’t work

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/iOS#12] opened 2022-01-02 00:25 UTC
Tapping the delete button in the  loadout sheet or page does nothing. My assumption is that this is due to the confirmation dialogue we pop up here.

**Comment by kyleshay** [comment] 2022-01-02 08:45
Ah thanks! I patched this but an having a heck of a time with the review process. #3

I'll give it another try with them

**Comment by bhollis** [comment] 2022-01-02 21:12
Duplicate of DestinyItemManager/iOS#3

**Closed by bhollis** 2022-01-02 21:12 UTC

**Comment by kyleshay** [comment] 2022-01-03 16:54
FYI looks like apple finally pushed the update! Should be fixed now.
